language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
env:
  - secure: "a02Px0vQ3TS9E1QdmZB18SNd3K2vGd8HRT+7JvGhEJspaRvvRNMJF8BCcncJCetvfQ2qewiPQhHNvsO9ckBlJXPcIZIpevaFRElsvXrOXJ9mB8IVWZ5bKfuNHGNH/jdACIbsFM9bq28hD2fj+Z6OI+Mpvm5ULbdxCWc3J9G8bqi+onJLCr52s/3Um8Z+xYs4ZyGegGLni+u5GOLuGsLSSlBaoJbuP9k78Z6Da80gH0zt04VgsuC1TTgP/NZzFRsBUgwE0ahzFw7YshbqxlH1VnXLbiURDxl/IxtjHPcOL8WzFt9emdU6yaoHLC9LAS5Dhau6ox4tXWSDMn8nfL1YsLml03UmYC3EYRNo+/U/nmqpcPv+Jl/bRa16wyjN4ZQ5e6jkS3V1Y9+zK84kyjmkIzdWooufRWMs6f65MfGZQG2ziCdUYMY5zuJvyKXDWr/WzKFSpH8uwmt54VLttwwtVWQf6Bo4HZ0pkN163AzAqTMAocVxIakbsxXzmM0LCT/rKTjSWkjI2tObiHEVUpD/3nwpT0Aiz2uym4C7lK3oUvz1DnWuDAWMHo1FXgb0XcVC33vh62XHecOguY2NvAdlNkKYLTEy/hmHGoltWBwnAOehrUB+8C60O+4nC7KdtBGJm7d6czIlSL+3Vp6bHjTTG6Dg4w6g3vlxDgAfvJPS1C8="
cache: bundler
script: bundle install && bundle exec rspec spec/
deploy:
  provider: rubygems
  api_key: $GEM_TOKEN
  gem: kontena-plugin-shell
  on:
    tags: true
