language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
env:
  - secure: "ZBBmWvy2I9koQ3UKHgQtcAdcBzrjFlmlERMQisBMK38vh2iwwj4fIaMaet4QLCZOn14BqnhB7Lympk8vWX1tjmlgIpwf5ehiJQHWnXTMhRdtJNed60WFvqVx5OArvMmcjCMJZ71bZSMzKA/uUEhcMMzf18pid4BYtUBPV8lVtAk28kj+349OT62sITH/qckyFutGD/kMrldM7XNtLJlpbghtQTB+dCfjvTeMDeIsaT5Yk6Fr0sE+h+YHWttzAlTJlGWSSd4dc9wnxFed0SuCAM267N075iZjQ505EATLb3ELnwp2OEvltXWCO38HU58OOqLJURzizShrREBOjUzuLWxjTQAJXumLxVp/qF8uQ2pgjO1mXwbbyMm78W1LnlLOEcqno+S6pD8hsLHVK9fV9Ftj1/4+XZ/xY+ojDnzAwqNHzxxlA9xYk6FUJqQM1d8HEedg3OlDtGMlohIcmj2n94oFzn1oSxcHqqELlzwYdTjO9Ckqo+SSyzoXo07tnpwBnfCWVswJSQTwNWzFNIsUnmsia8DW2De8EEf1YElt8RHHXLerW/ODbQrAfYXXUWcFNhl7x8strnP7wqegMDIPuOiSK4d7KoajeS8A41G/Fwt3S9IR6PO+q9/yRsoMfaz7+PnHNsw5UbeFIhL4kPq7FG2zKlq+j7vrxszQVb4fmdU="
cache: bundler
script: bundle install && bundle exec rspec spec/
deploy:
  provider: rubygems
  api_key: $GEM_TOKEN
  gem: kontena-plugin-shell
  on:
    tags: true
