language: ruby
rvm:
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
env:
  - secure: "C0lxYoafJusn2xk8JEWIpKE1I6EuCIcJRdlvCOB0PbyS8thgu8PP7x0VeqxSB16WwjBwF43bThKYF6xYA5kp36xHSU6uGV+5ZPxdiDPcplsKrtaAGN9DXvWFVxeob4Zi3oG6FmtgYNi/Duf+c0RMT0K2AmJHneay/0dJ3xM5S8BN7kNiNDWs4QDlUq1oU/Hiaf8+kb5kGa6eU9gjyxtxH4+aLMCta1s+m2abIB9Kn+nr5UKgF3myaistn1I5rAnb42a9tEffoNiP+k75IhNLUhnjvIeffFij+vPqpSWMn3W1jKvKYOJ/a6XffIomx8fTuJZM594zcHmsqDzI6X5/j2YOrLF3SVCp9g3ydsI4cXM0r02x/+KX4QdPYFQXIQbHrCWhFrCLfESAsR9kC9Z1hLJaGCWo8leM2wXCjVkF9BJmnhjfPzj4expdk63jxsO6kZyVjgIkanA+cT78WNsFNBYTlh4XTtMx+WgaLQvjswe3lOQEDg+rujPP6iD5tMVac0mbHQNmlSnxn7zUQ6XtVI/nhCcgiNen++alUu6bDksLFCYRXcF3TwIeu3RBQUIaMI6poQz/owu+QsQoujj2TJtAJCYOkrJVlQq+qHFrrek9vhLuJvwMOpH17jAaxaVqr0y3ZnJVxDnF/UPsEakTiV6CoLxLOrac3sf7UY2PKms="
cache: bundler
script: bundle install && bundle exec rspec spec/
deploy:
  provider: rubygems
  api_key: $GEM_TOKEN
  gem: kontena-plugin-shell
  on:
    tags: true
